<script setup lang="ts">
import SearchBar from "../components/SearchBar.vue";
import {useRouter} from 'vue-router';
const router = useRouter();
async function search(val: string){ 
  //console.log(val)
  router.push({path:'/search', query:{ query : val}})

}
</script>

<template>
      <div class="w-full mt-20 pt-20">
        <h1 class="text-4xl text-center">Welcome to </h1> 
        <h1 class="text-5xl text-center">
            <span class="inline-block scale-in-center text-orange-400 font-bold">Vue</span>
            <span class="inline-block scale-in-center delay-300">The</span>
            <span class="inline-block scale-in-center text-orange-400 font-extrabold delay-700">Menue</span></h1>
      </div>

      <p class="text-center text-lg mt-5">
        This is a personal project from <a href="https://github.com/Giuliano1993" class="text-white underline decoration-orange-400" target="_blank">Giuliano Gostinfini</a> for playing around with code and food together.
      </p>
      <p class="text-center text-lg">
        Hope you hav a nice stay
      </p>
      <div class="text-center">
        <SearchBar class="w-1/2 mt-5" @changedSearch="search"></SearchBar>
      </div>
</template>
<style scoped>
/*.scale-in-center {
	-webkit-animation: scale-in-center 0.5s cubic-bezier(0.250, 0.460, 0.450, 0.940) both;
	        animation: scale-in-center 0.5s cubic-bezier(0.250, 0.460, 0.450, 0.940) both;
}*/
span.scale-in-center:nth-child(1){
  -webkit-animation: scale-in-center 0.5s cubic-bezier(0.250, 0.460, 0.450, 0.940) both;
	        animation: scale-in-center 0.5s cubic-bezier(0.250, 0.460, 0.450, 0.940) both;
}
span.scale-in-center:nth-child(2){
  -webkit-animation: scale-in-center 0.5s cubic-bezier(0.250, 0.460, 0.450, 0.940) 0.5s both;
	        animation: scale-in-center 0.5s cubic-bezier(0.250, 0.460, 0.450, 0.940) 0.5s both;
}
span.scale-in-center:nth-child(3){
  -webkit-animation: scale-in-center 0.5s cubic-bezier(0.250, 0.460, 0.450, 0.940) 1s both;
	        animation: scale-in-center 0.5s cubic-bezier(0.250, 0.460, 0.450, 0.940) 1s both;
}


/* ----------------------------------------------
 * Generated by Animista on 2022-11-15 19:11:11
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation scale-in-center
 * ----------------------------------------
 */
 @-webkit-keyframes scale-in-center {
  0% {
    -webkit-transform: scale(0);
            transform: scale(0);
    opacity: 1;
  }
  100% {
    -webkit-transform: scale(1);
            transform: scale(1);
    opacity: 1;
  }
}
@keyframes scale-in-center {
  0% {
    -webkit-transform: scale(0);
            transform: scale(0);
    opacity: 1;
  }
  100% {
    -webkit-transform: scale(1);
            transform: scale(1);
    opacity: 1;
  }
}


</style>
